
rule SmartThingsEdgeDriverLua
{
    meta:
        description = "YARA rule to match SmartThings Edge Driver Lua source code based on variable identifiers"
        author = "Huan Bui"

    strings:
        $test_0 = "test"
        $capabilities_1 = "capabilities"
        $data_types_2 = "data_types"
        $zcl_clusters_3 = "zcl_clusters"
        $zigbee_test_utils_4 = "zigbee_test_utils"
        $t_utils_5 = "t_utils"
        $utils_6 = "utils"
        $tuya_types_7 = "tuya_types"
        $profile_8 = "profile"
        $get_profile_definition_9 = "get_profile_definition"
        $load_all_caps_from_profile_10 = "load_all_caps_from_profile"
        $mock_parent_device_11 = "mock_parent_device"
        $build_test_zigbee_device_12 = "build_test_zigbee_device"
        $zigbee_endpoints_13 = "zigbee_endpoints"
        $id_14 = "id"
        $manufacturer_15 = "manufacturer"
        $model_16 = "model"
        $server_clusters_17 = "server_clusters"
        $client_clusters_18 = "client_clusters"
        $fingerprinted_endpoint_id_19 = "fingerprinted_endpoint_id"
        $test_init_20 = "test_init"
        $function_21 = "function"
        $send_spell_22 = "send_spell"
        $add_test_device_23 = "add_test_device"
        $register_message_test_24 = "register_message_test"
        $channel_25 = "channel"
        $direction_26 = "direction"
        $message_27 = "message"
        $McuSyncTime_28 = "McuSyncTime"
        $expect_spell_29 = "expect_spell"
        $expect_settings_30 = "expect_settings"
        $style_31 = "style"
        $align_32 = "align"
        $zigbee_33 = "zigbee"
        $build_test_rx_34 = "build_test_rx"
        $Boolean_35 = "Boolean"
        $generate_test_message_36 = "generate_test_message"
        $present_37 = "present"
        $Uint32_38 = "Uint32"
        $illuminance_39 = "illuminance"
        $generate_info_changed_40 = "generate_info_changed"
        $preferences_41 = "preferences"
        $prefSensitivity_42 = "prefSensitivity"
        $prefNearDetection_43 = "prefNearDetection"
        $prefFarDetection_44 = "prefFarDetection"
        $prefDetectionDelay_45 = "prefDetectionDelay"
        $prefFadingTime_46 = "prefFadingTime"
        $DataRequest_47 = "DataRequest"

    condition:
        any of them
}
